# Generated by Django 3.1.7 on 2021-03-13 16:32

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the name of project', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Bugreports',
            fields=[
                ('bugid', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular bug', primary_key=True, serialize=False)),
                ('Assignee', models.CharField(max_length=200)),
                ('Summary', models.TextField(help_text='Enter a brief description of the bug', max_length=1000)),
                ('Status', models.CharField(choices=[('fixed', 'Fixed'), ('worksforme', 'Worksforme'), ('duplicate', 'Duplicate'), ('wontfix', 'Wontfix'), ('open', 'Open')], default='open', help_text='Status Type', max_length=200)),
                ('Severity', models.CharField(choices=[('m', 'Major'), ('n', 'Normal'), ('b', 'Blocker'), ('c', 'Critical'), ('mi', 'Minor'), ('t', 'Trivial'), ('e', 'Enhancement')], default='n', help_text='Severity Type', max_length=2)),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='bugSystem.project')),
            ],
        ),
    ]
