# Generated by Django 3.1.7 on 2021-03-17 15:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bugSystem', '0003_project_teammember'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='teamMember',
        ),
        migrations.AddField(
            model_name='project',
            name='teamMember',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
