# Generated by Django 3.1.7 on 2021-03-17 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bugSystem', '0004_auto_20210317_2059'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bugreports',
            options={'permissions': (('can_view_all_bugreports', 'View All bug reports'),)},
        ),
    ]
