# Generated by Django 3.1.7 on 2021-03-19 15:31

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bugSystem', '0005_auto_20210317_2318'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bugreports',
            new_name='Bugreport',
        ),
    ]
