# Generated by Django 3.1.7 on 2021-03-21 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bugSystem', '0007_bugreport_project_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bugreport',
            options={'permissions': (('can_view_all_bugreports', 'View All bug reports'), ('can_file_new_bugreport', 'Can file new bugreport'))},
        ),
    ]
