# Generated by Django 3.1.7 on 2021-03-25 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugSystem', '0008_auto_20210321_2109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bugreport',
            name='Severity',
            field=models.CharField(choices=[('Major', 'Major'), ('Normal', 'Normal'), ('Blocker', 'Blocker'), ('Critical', 'Critical'), ('Minor', 'Minor'), ('Trivial', 'Trivial'), ('Enhancement', 'Enhancement')], default='Normal', help_text='Severity Type', max_length=200),
        ),
        migrations.AlterField(
            model_name='bugreport',
            name='Status',
            field=models.CharField(choices=[('Fixed', 'Fixed'), ('Worksforme', 'Worksforme'), ('Duplicate', 'Duplicate'), ('Wontfix', 'Wontfix'), ('Open', 'Open')], default='open', help_text='Status Type', max_length=200),
        ),
    ]
